//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int id_direccion { get; set; }
        public int id_usuario { get; set; }
        public string provincia { get; set; }
        public string canton { get; set; }
        public string distrito { get; set; }
        public string detalles { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
