//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialPunto
    {
        public int id_historial { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> puntos_ganados { get; set; }
        public Nullable<int> puntos_utilizados { get; set; }
        public Nullable<System.DateTime> fecha_movimiento { get; set; }
        public string descripcion { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
