//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AgataMakeUpDBEntities : DbContext
    {
        public AgataMakeUpDBEntities()
            : base("name=AgataMakeUpDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carrito> Carritoes { get; set; }
        public virtual DbSet<CarritoDetalle> CarritoDetalles { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Direccion> Direccions { get; set; }
        public virtual DbSet<ErrorSistema> ErrorSistemas { get; set; }
        public virtual DbSet<Favorito> Favoritoes { get; set; }
        public virtual DbSet<HistorialPunto> HistorialPuntos { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Pedido> Pedidoes { get; set; }
        public virtual DbSet<PedidoDetalle> PedidoDetalles { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<ProductoPromocion> ProductoPromocions { get; set; }
        public virtual DbSet<Promocion> Promocions { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual int spRegistrarError(string mensaje, Nullable<System.DateTime> fechaHora, string lugar, Nullable<int> idUsuario)
        {
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("Mensaje", mensaje) :
                new ObjectParameter("Mensaje", typeof(string));
    
            var fechaHoraParameter = fechaHora.HasValue ?
                new ObjectParameter("FechaHora", fechaHora) :
                new ObjectParameter("FechaHora", typeof(System.DateTime));
    
            var lugarParameter = lugar != null ?
                new ObjectParameter("Lugar", lugar) :
                new ObjectParameter("Lugar", typeof(string));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRegistrarError", mensajeParameter, fechaHoraParameter, lugarParameter, idUsuarioParameter);
        }
    }
}
