//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.HistorialPuntos = new HashSet<HistorialPunto>();
            this.PedidoDetalles = new HashSet<PedidoDetalle>();
        }
    
        public int id_pedido { get; set; }
        public int id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_pedido { get; set; }
        public string estado { get; set; }
        public decimal subtotal { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public decimal total { get; set; }
        public Nullable<int> id_direccion { get; set; }
        public string provincia_entrega { get; set; }
        public string canton_entrega { get; set; }
        public string distrito_entrega { get; set; }
        public string detalles_entrega { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialPunto> HistorialPuntos { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoDetalle> PedidoDetalles { get; set; }
        public virtual Direccion Direccion { get; set; }
    }
}
