//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoPromocion
    {
        public int id_producto_promocion { get; set; }
        public int id_producto { get; set; }
        public int id_promocion { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Promocion Promocion { get; set; }
    }
}
